### ISSUE TITLE
_get_comp_words_by_ref: command not found

### ISSUE THREAD

**Issue by koenhendriks** [bramus/composer-autocomplete#2]
Hello,

I'm trying to use this on macOS. After installation I type `composer [TAB][TAB]` and get the following error:

`composer -bash: _get_comp_words_by_ref: command not found`

Image for clarification:
![Screenshot 2019-05-31 at 09 43 24](https://user-images.githubusercontent.com/4124579/58689894-8dd75080-8388-11e9-9ab6-c154a9b348a7.png)

I've tried installing bash-autocompletion with `brew install bash-completion` but that didn't work.

**Comment by bramus** [comment]
Which version of macOS and which terminal are you using? I’m using the default “Terminal.app” that ships with macOS.

**Comment by koenhendriks** [comment]
macOS MOjave 10.14.5 

I've tried all the terminals, here is a screenshot with iTerm, Hyper and stock Terminal.

![Screenshot 2019-05-31 at 13 16 25](https://user-images.githubusercontent.com/4124579/58702518-4fe92500-83a6-11e9-807b-e4d3a5852575.png)

**Comment by bramus** [comment]
Does the solution from https://github.com/jweslley/rails_completion/issues/2#issuecomment-432823013 help?

**Comment by miclf** [comment]
Same issue here, using iTerm on macOS 10.14.

The proposed solution doesn’t work because there is no `/usr/local/etc/profile.d` directory on my system.

That said, there is a `/usr/local/etc/bash_completions.d` but, looking at its contents, it seems to be managed by the [Homebrew package manager](https://brew.sh/) and I cannot find any script there that seems to be shipped by default with macOS.

**Comment by bramus** [comment]
Thanks for the extra info @miclf.

I also have the `bash_completion.d` directory present on my system, whose contents indeed seem to resemble Homebrew packages I have installed.

```
$ ls $(brew --prefix)/etc/bash_completion
aws_bash_completer          brew-services               git-completion.bash         mas                         tig-completion.bash         youtube-dl.bash-completion
brew                        flow-completion.bash        git-prompt.sh               npm                         tmux
```

Although not enabled, [these can be loaded onto your system as per Homebrew docs](https://docs.brew.sh/Shell-Completion#configuring-completions-in-bash)

This leaves me wondering: which version of brew are y'all running? Here I'm running version 2.1.3:

```
$ brew --version
Homebrew 2.1.3
Homebrew/homebrew-core (git revision e47f3; last commit 2019-05-22)
Homebrew/homebrew-cask (git revision c7c95; last commit 2019-05-22)
```

Although I can't find anything specific in the Hombrew changelog, but perhaps older Homebrew versions are coupled with older versions of bash-completion _(version 2 is required)_?

**Comment by koenhendriks** [comment]
> Does the solution from [jweslley/rails_completion#2 (comment)](https://github.com/jweslley/rails_completion/issues/2#issuecomment-432823013) help?

This worked for me 👍 

After doing    
`brew install bash-completion`

I had to add   
`source /usr/local/etc/profile.d/bash_completion.sh`

to my `~/.bashrc` 

Thanks!


Homebrew I'm using:

```bash
koenhendriks@Hendriks-MacBook-Pro:~$ brew --version
Homebrew 2.1.4
Homebrew/homebrew-core (git revision 35b85; last commit 2019-05-30)
Homebrew/homebrew-cask (git revision c161a; last commit 2019-05-31)
```
